---
# tasks file for mrleerkotte.postfix-relay
- name: Ensure Postfix is installed
  become: true
  ansible.builtin.package:
    name: postfix
    state: present

- name: Ensure Postfix is set to start at boot
  become: true
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: yes

- name: Enable SMTP over TLS if true
  become: true
  ansible.builtin.lineinfile:
    path: '{{ postfix_config_file }}'
    regexp: '^smtp_use_tls\s?='
    line: "smtp_use_tls = yes"
  when: postfix_relay_tls

- name: Enable from address rewriting
  become: true
  ansible.builtin.lineinfile:
    path: '{{ postfix_config_file }}'
    regexp: '^smtp_generic_maps\s?='
    line: "smtp_generic_maps = hash:{{ postfix_rewrite_from_map }}"
  when: postfix_rewrite_from_address 

- name: Template out generic map
  become: true
  ansible.builtin.template:
    src: generic.j2
    dest: '{{ postfix_rewrite_from_map }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: postmap rewrite

- name: Ensure smarthost is set
  become: true
  ansible.builtin.lineinfile:
    path: '{{ postfix_config_file }}'
    regexp: '^relayhost\s?='
    line: "relayhost = {{ postfix_relay_host }}"
  notify: restart postfix service
