---
# handlers file for mrleerkotte.postfix-relay
- name: restart postfix service
  become: true
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: postmap rewrite
  become: true
  ansible.builtin.command: postmap {{ postfix_rewrite_from_map }}